version: 2
updates:
  - package-ecosystem: gomod
    directory: /nashorn/
    schedule:
      interval: daily
  - package-ecosystem: gomod
    directory: /reverseshell/
    schedule:
      interval: daily
  - package-ecosystem: gomod
    directory: /webshell/
    schedule:
      interval: daily
